# Supported funding platforms for Evilwaf

github: [matrixleons]           # GitHub Sponsors username (ako) 
patreon: matrixleons             # Patreon username yako
open_collective: evilwaf         # Open Collective username/project
ko_fi: matrixleons                # Ko-fi username/link yako
tidelift: ""                      #  empty
community_bridge: ""              # empty
liberapay: matrixleons            # Liberapay username yako
issuehunt: ""                      #empty
otechie: ""                       #empty
custom:
