# Supported funding platforms for Evilwaf

github: [matrixleons]           # GitHub Sponsors 
patreon: matrixleons             # 
open_collective: evilwaf         # 
liberapay: matrixleons            # Liberapay u
